apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname.short" . }}-service
  namespace: {{.Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: grpc
    protocol: TCP
  selector:
    app: {{ include "fullname.short" . }}
