image:
  # image.registry -- Registry containing the image for the Kommoner operator
  registry: ghcr.io
  # image.repository -- Repository containing the image for the Kommoner operator
  repository: stackvista/sts-otel-bridge
  # image.tag -- Tag of the image for the Kommoner operator
  tag: v0.0.1
  # image.pullPolicy -- Pull policy for the image for the Kommoner operator
  pullPolicy: IfNotPresent
# nodeSelector:
#   node.kubernetes.io/purpose-core: "yes"

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi
# tolerations:
# - effect: NoSchedule
#   operator: Exists
# securityContext -- SecurityContext for the Kommoner pod
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
